Feature/process file
nhsuk/pomi-data-etl pull request #2
Opened 2017-03-09 17:33 UTC by st3v3nhunt

This is good for review, additional info has been added to the `README` about running the app.

More tests are needed which I'll be working on next along with looking at how to get this data into the db.

I'm also interested in seeing whether the file can be streamed rather than downloading initially.

2017-03-10 10:01 UTC, markysoft requested changes
Suggestions to simplify promise handling

2017-03-10 10:01 UTC, markysoft commented on app/lib/downloadFile.js
> +  return new Promise((resolve, reject) => {
The API request already returns a promise, the wrapping promise isn't required and the body could be written as 

```
 log.time('Downloading the POMI file took');
 return apiRequest(POMI_DOWNLOAD_LOCATION)
   .then((data) => {
     log.timeEnd('Downloading the POMI file took');
     fsHelper.saveFileSync(data, POMI_FILE);
   });
```

2017-03-10 10:01 UTC, markysoft commented on app/lib/getLatestPeriod.js
> +
As this method is called from a previous promise it is auto-magically wrapped in a promise so a new Promise isn't required. The body could just be
```
  log.time('Getting latest period took');
  const latestPeriod = utils.getMostRecentPeriod(periods);
  log.timeEnd('Getting latest period took');
  log.info(`Latest period is ${latestPeriod}`);
  return latestPeriod;
```

2017-03-10 14:29 UTC, st3v3nhunt commented
@markysoft Changes made.

2017-03-11 11:43 UTC, markysoft approved these changes
LGTM

2017-03-11 11:44 UTC, merged